name: React CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build, Deploy to S3 Bucket
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.16.x]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: npm version
        run: nvm use 7.20.1
        working-directory: ${{ secrets.working_directory }}
  
      

